algoritmo "Dados"
var
nome:caractere
email:caractere
idade:inteiro
nomeFilme:caractere
inicio
escreval("Qual é seu nome"?)
leia(nome)
escreval("Qual é seu email"?)
leia(email)
escreval("Qual é sua idade"?)
leia(idade)
escreval("Qual é seu filme favorito"?)
leia(nomeFilme)
escreval()

escreval("Seu nome é ", nome, " Seu email é ", email, " Sua idade é ", idade, " Seu filme favorito é ", nomeFilme)


fimalgoritmo